export type ThemeConfig = {
  name: string;
  label: string;
  cssVars: {
    light: Record<string, string>;
    dark: Record<string, string>;
  };
};

export const themes: ThemeConfig[] = [
  {
    name: "zinc",
    label: "Zinc (Default)",
    cssVars: {
      light: {
        "--background": "#ffffff",
        "--foreground": "#09090b",
        "--card": "#ffffff",
        "--card-foreground": "#09090b",
        "--popover": "#ffffff",
        "--popover-foreground": "#09090b",
        "--primary": "#18181b",
        "--primary-foreground": "#fafafa",
        "--secondary": "#f4f4f5",
        "--secondary-foreground": "#18181b",
        "--muted": "#f4f4f5",
        "--muted-foreground": "#71717a",
        "--accent": "#f4f4f5",
        "--accent-foreground": "#18181b",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#fafafa",
        "--border": "#e4e4e7",
        "--input": "#e4e4e7",
        "--ring": "#18181b",
      },
      dark: {
        "--background": "#09090b",
        "--foreground": "#fafafa",
        "--card": "#09090b",
        "--card-foreground": "#fafafa",
        "--popover": "#09090b",
        "--popover-foreground": "#fafafa",
        "--primary": "#fafafa",
        "--primary-foreground": "#18181b",
        "--secondary": "#27272a",
        "--secondary-foreground": "#fafafa",
        "--muted": "#27272a",
        "--muted-foreground": "#a1a1aa",
        "--accent": "#27272a",
        "--accent-foreground": "#fafafa",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#fafafa",
        "--border": "#27272a",
        "--input": "#27272a",
        "--ring": "#d4d4d8",
      },
    },
  },
  {
    name: "slate",
    label: "Slate",
    cssVars: {
      light: {
        "--background": "#ffffff",
        "--foreground": "#0f172a",
        "--card": "#ffffff",
        "--card-foreground": "#0f172a",
        "--popover": "#ffffff",
        "--popover-foreground": "#0f172a",
        "--primary": "#0f172a",
        "--primary-foreground": "#f8fafc",
        "--secondary": "#f1f5f9",
        "--secondary-foreground": "#0f172a",
        "--muted": "#f1f5f9",
        "--muted-foreground": "#64748b",
        "--accent": "#f1f5f9",
        "--accent-foreground": "#0f172a",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#f8fafc",
        "--border": "#e2e8f0",
        "--input": "#e2e8f0",
        "--ring": "#0f172a",
      },
      dark: {
        "--background": "#020617",
        "--foreground": "#f8fafc",
        "--card": "#020617",
        "--card-foreground": "#f8fafc",
        "--popover": "#020617",
        "--popover-foreground": "#f8fafc",
        "--primary": "#f8fafc",
        "--primary-foreground": "#0f172a",
        "--secondary": "#1e293b",
        "--secondary-foreground": "#f8fafc",
        "--muted": "#1e293b",
        "--muted-foreground": "#94a3b8",
        "--accent": "#1e293b",
        "--accent-foreground": "#f8fafc",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#f8fafc",
        "--border": "#1e293b",
        "--input": "#1e293b",
        "--ring": "#cbd5e1",
      },
    },
  },
  {
    name: "stone",
    label: "Stone",
    cssVars: {
      light: {
        "--background": "#ffffff",
        "--foreground": "#1c1917",
        "--card": "#ffffff",
        "--card-foreground": "#1c1917",
        "--popover": "#ffffff",
        "--popover-foreground": "#1c1917",
        "--primary": "#1c1917",
        "--primary-foreground": "#fafaf9",
        "--secondary": "#f5f5f4",
        "--secondary-foreground": "#1c1917",
        "--muted": "#f5f5f4",
        "--muted-foreground": "#78716c",
        "--accent": "#f5f5f4",
        "--accent-foreground": "#1c1917",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#fafaf9",
        "--border": "#e7e5e4",
        "--input": "#e7e5e4",
        "--ring": "#1c1917",
      },
      dark: {
        "--background": "#0c0a09",
        "--foreground": "#fafaf9",
        "--card": "#0c0a09",
        "--card-foreground": "#fafaf9",
        "--popover": "#0c0a09",
        "--popover-foreground": "#fafaf9",
        "--primary": "#fafaf9",
        "--primary-foreground": "#1c1917",
        "--secondary": "#292524",
        "--secondary-foreground": "#fafaf9",
        "--muted": "#292524",
        "--muted-foreground": "#a8a29e",
        "--accent": "#292524",
        "--accent-foreground": "#fafaf9",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#fafaf9",
        "--border": "#292524",
        "--input": "#292524",
        "--ring": "#d6d3d1",
      },
    },
  },
  {
    name: "blue",
    label: "Blue",
    cssVars: {
      light: {
        "--background": "#ffffff",
        "--foreground": "#020817",
        "--card": "#ffffff",
        "--card-foreground": "#020817",
        "--popover": "#ffffff",
        "--popover-foreground": "#020817",
        "--primary": "#2563eb",
        "--primary-foreground": "#f8fafc",
        "--secondary": "#f1f5f9",
        "--secondary-foreground": "#0f172a",
        "--muted": "#f1f5f9",
        "--muted-foreground": "#64748b",
        "--accent": "#f1f5f9",
        "--accent-foreground": "#0f172a",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#f8fafc",
        "--border": "#e2e8f0",
        "--input": "#e2e8f0",
        "--ring": "#2563eb",
      },
      dark: {
        "--background": "#020817",
        "--foreground": "#f8fafc",
        "--card": "#020817",
        "--card-foreground": "#f8fafc",
        "--popover": "#020817",
        "--popover-foreground": "#f8fafc",
        "--primary": "#3b82f6",
        "--primary-foreground": "#020817",
        "--secondary": "#1e293b",
        "--secondary-foreground": "#f8fafc",
        "--muted": "#1e293b",
        "--muted-foreground": "#94a3b8",
        "--accent": "#1e293b",
        "--accent-foreground": "#f8fafc",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#f8fafc",
        "--border": "#1e293b",
        "--input": "#1e293b",
        "--ring": "#3b82f6",
      },
    },
  },
  {
    name: "violet",
    label: "Violet",
    cssVars: {
      light: {
        "--background": "#ffffff",
        "--foreground": "#030712",
        "--card": "#ffffff",
        "--card-foreground": "#030712",
        "--popover": "#ffffff",
        "--popover-foreground": "#030712",
        "--primary": "#7c3aed",
        "--primary-foreground": "#f9fafb",
        "--secondary": "#f3f4f6",
        "--secondary-foreground": "#111827",
        "--muted": "#f3f4f6",
        "--muted-foreground": "#6b7280",
        "--accent": "#f3f4f6",
        "--accent-foreground": "#111827",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#f9fafb",
        "--border": "#e5e7eb",
        "--input": "#e5e7eb",
        "--ring": "#7c3aed",
      },
      dark: {
        "--background": "#030712",
        "--foreground": "#f9fafb",
        "--card": "#030712",
        "--card-foreground": "#f9fafb",
        "--popover": "#030712",
        "--popover-foreground": "#f9fafb",
        "--primary": "#8b5cf6",
        "--primary-foreground": "#030712",
        "--secondary": "#1f2937",
        "--secondary-foreground": "#f9fafb",
        "--muted": "#1f2937",
        "--muted-foreground": "#9ca3af",
        "--accent": "#1f2937",
        "--accent-foreground": "#f9fafb",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#f9fafb",
        "--border": "#1f2937",
        "--input": "#1f2937",
        "--ring": "#8b5cf6",
      },
    },
  },
  {
    name: "green",
    label: "Green",
    cssVars: {
      light: {
        "--background": "#ffffff",
        "--foreground": "#022c22",
        "--card": "#ffffff",
        "--card-foreground": "#022c22",
        "--popover": "#ffffff",
        "--popover-foreground": "#022c22",
        "--primary": "#10b981",
        "--primary-foreground": "#ffffff",
        "--secondary": "#f0fdf4",
        "--secondary-foreground": "#064e3b",
        "--muted": "#f0fdf4",
        "--muted-foreground": "#059669",
        "--accent": "#f0fdf4",
        "--accent-foreground": "#064e3b",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--border": "#e2e8f0",
        "--input": "#e2e8f0",
        "--ring": "#10b981",
      },
      dark: {
        "--background": "#022c22",
        "--foreground": "#f8fafc",
        "--card": "#022c22",
        "--card-foreground": "#f8fafc",
        "--popover": "#022c22",
        "--popover-foreground": "#f8fafc",
        "--primary": "#10b981",
        "--primary-foreground": "#022c22",
        "--secondary": "#064e3b",
        "--secondary-foreground": "#f8fafc",
        "--muted": "#064e3b",
        "--muted-foreground": "#34d399",
        "--accent": "#064e3b",
        "--accent-foreground": "#f8fafc",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#f8fafc",
        "--border": "#064e3b",
        "--input": "#064e3b",
        "--ring": "#10b981",
      },
    },
  },
  {
    name: "orange",
    label: "Orange",
    cssVars: {
      light: {
        "--background": "#ffffff",
        "--foreground": "#0c0a09",
        "--card": "#ffffff",
        "--card-foreground": "#0c0a09",
        "--popover": "#ffffff",
        "--popover-foreground": "#0c0a09",
        "--primary": "#f97316",
        "--primary-foreground": "#fafaf9",
        "--secondary": "#f5f5f4",
        "--secondary-foreground": "#1c1917",
        "--muted": "#f5f5f4",
        "--muted-foreground": "#78716c",
        "--accent": "#f5f5f4",
        "--accent-foreground": "#1c1917",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#fafaf9",
        "--border": "#e7e5e4",
        "--input": "#e7e5e4",
        "--ring": "#f97316",
      },
      dark: {
        "--background": "#0c0a09",
        "--foreground": "#fafaf9",
        "--card": "#0c0a09",
        "--card-foreground": "#fafaf9",
        "--popover": "#0c0a09",
        "--popover-foreground": "#fafaf9",
        "--primary": "#ea580c",
        "--primary-foreground": "#fafaf9",
        "--secondary": "#292524",
        "--secondary-foreground": "#fafaf9",
        "--muted": "#292524",
        "--muted-foreground": "#a8a29e",
        "--accent": "#292524",
        "--accent-foreground": "#fafaf9",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#fafaf9",
        "--border": "#292524",
        "--input": "#292524",
        "--ring": "#ea580c",
      },
    },
  },
  {
    name: "yellow",
    label: "Yellow",
    cssVars: {
      light: {
        "--background": "#ffffff",
        "--foreground": "#0c0a09",
        "--card": "#ffffff",
        "--card-foreground": "#0c0a09",
        "--popover": "#ffffff",
        "--popover-foreground": "#0c0a09",
        "--primary": "#eab308",
        "--primary-foreground": "#1c1917",
        "--secondary": "#f5f5f4",
        "--secondary-foreground": "#1c1917",
        "--muted": "#f5f5f4",
        "--muted-foreground": "#78716c",
        "--accent": "#f5f5f4",
        "--accent-foreground": "#1c1917",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#fafaf9",
        "--border": "#e7e5e4",
        "--input": "#e7e5e4",
        "--ring": "#eab308",
      },
      dark: {
        "--background": "#0c0a09",
        "--foreground": "#fafaf9",
        "--card": "#0c0a09",
        "--card-foreground": "#fafaf9",
        "--popover": "#0c0a09",
        "--popover-foreground": "#fafaf9",
        "--primary": "#facc15",
        "--primary-foreground": "#1c1917",
        "--secondary": "#292524",
        "--secondary-foreground": "#fafaf9",
        "--muted": "#292524",
        "--muted-foreground": "#a8a29e",
        "--accent": "#292524",
        "--accent-foreground": "#fafaf9",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#fafaf9",
        "--border": "#292524",
        "--input": "#292524",
        "--ring": "#facc15",
      },
    },
  },
  {
    name: "rose",
    label: "Rose",
    cssVars: {
      light: {
        "--background": "#ffffff",
        "--foreground": "#09090b",
        "--card": "#ffffff",
        "--card-foreground": "#09090b",
        "--popover": "#ffffff",
        "--popover-foreground": "#09090b",
        "--primary": "#e11d48",
        "--primary-foreground": "#ffffff",
        "--secondary": "#f4f4f5",
        "--secondary-foreground": "#18181b",
        "--muted": "#f4f4f5",
        "--muted-foreground": "#71717a",
        "--accent": "#f4f4f5",
        "--accent-foreground": "#18181b",
        "--destructive": "#e11d48",
        "--destructive-foreground": "#ffffff",
        "--border": "#e4e4e7",
        "--input": "#e4e4e7",
        "--ring": "#e11d48",
      },
      dark: {
        "--background": "#09090b",
        "--foreground": "#fafafa",
        "--card": "#09090b",
        "--card-foreground": "#fafafa",
        "--popover": "#09090b",
        "--popover-foreground": "#fafafa",
        "--primary": "#e11d48",
        "--primary-foreground": "#ffffff",
        "--secondary": "#27272a",
        "--secondary-foreground": "#fafafa",
        "--muted": "#27272a",
        "--muted-foreground": "#a1a1aa",
        "--accent": "#27272a",
        "--accent-foreground": "#fafafa",
        "--destructive": "#e11d48",
        "--destructive-foreground": "#ffffff",
        "--border": "#27272a",
        "--input": "#27272a",
        "--ring": "#e11d48",
      },
    },
  },
  {
    name: "midnight",
    label: "Midnight",
    cssVars: {
      light: {
        "--background": "#f8fafc",
        "--foreground": "#020617",
        "--card": "#ffffff",
        "--card-foreground": "#020617",
        "--popover": "#ffffff",
        "--popover-foreground": "#020617",
        "--primary": "#0f172a",
        "--primary-foreground": "#f8fafc",
        "--secondary": "#f1f5f9",
        "--secondary-foreground": "#0f172a",
        "--muted": "#f1f5f9",
        "--muted-foreground": "#64748b",
        "--accent": "#f1f5f9",
        "--accent-foreground": "#0f172a",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#f8fafc",
        "--border": "#e2e8f0",
        "--input": "#e2e8f0",
        "--ring": "#020617",
      },
      dark: {
        "--background": "#020617",
        "--foreground": "#f8fafc",
        "--card": "#0f172a",
        "--card-foreground": "#f8fafc",
        "--popover": "#0f172a",
        "--popover-foreground": "#f8fafc",
        "--primary": "#38bdf8",
        "--primary-foreground": "#020617",
        "--secondary": "#1e293b",
        "--secondary-foreground": "#f8fafc",
        "--muted": "#1e293b",
        "--muted-foreground": "#94a3b8",
        "--accent": "#1e293b",
        "--accent-foreground": "#f8fafc",
        "--destructive": "#7f1d1d",
        "--destructive-foreground": "#f8fafc",
        "--border": "#1e293b",
        "--input": "#1e293b",
        "--ring": "#38bdf8",
      },
    },
  },
  {
    name: "cyberpunk",
    label: "Cyberpunk",
    cssVars: {
      light: {
        "--background": "#fdfba7",
        "--foreground": "#050505",
        "--card": "#ffffff",
        "--card-foreground": "#050505",
        "--popover": "#ffffff",
        "--popover-foreground": "#050505",
        "--primary": "#ff003c",
        "--primary-foreground": "#ffffff",
        "--secondary": "#050505",
        "--secondary-foreground": "#ffffff",
        "--muted": "#e2e096",
        "--muted-foreground": "#505050",
        "--accent": "#050505",
        "--accent-foreground": "#ffffff",
        "--destructive": "#ff0000",
        "--destructive-foreground": "#ffffff",
        "--border": "#050505",
        "--input": "#050505",
        "--ring": "#ff003c",
      },
      dark: {
        "--background": "#050505",
        "--foreground": "#fdfba7",
        "--card": "#111111",
        "--card-foreground": "#fdfba7",
        "--popover": "#111111",
        "--popover-foreground": "#fdfba7",
        "--primary": "#fcee0a",
        "--primary-foreground": "#050505",
        "--secondary": "#ff003c",
        "--secondary-foreground": "#ffffff",
        "--muted": "#222222",
        "--muted-foreground": "#a0a0a0",
        "--accent": "#ff003c",
        "--accent-foreground": "#ffffff",
        "--destructive": "#ff0000",
        "--destructive-foreground": "#ffffff",
        "--border": "#333333",
        "--input": "#333333",
        "--ring": "#fcee0a",
      },
    },
  },
  {
    name: "nord",
    label: "Nord",
    cssVars: {
      light: {
        "--background": "#eceff4",
        "--foreground": "#2e3440",
        "--card": "#e5e9f0",
        "--card-foreground": "#2e3440",
        "--popover": "#e5e9f0",
        "--popover-foreground": "#2e3440",
        "--primary": "#5e81ac",
        "--primary-foreground": "#eceff4",
        "--secondary": "#81a1c1",
        "--secondary-foreground": "#eceff4",
        "--muted": "#d8dee9",
        "--muted-foreground": "#4c566a",
        "--accent": "#88c0d0",
        "--accent-foreground": "#2e3440",
        "--destructive": "#bf616a",
        "--destructive-foreground": "#eceff4",
        "--border": "#d8dee9",
        "--input": "#d8dee9",
        "--ring": "#5e81ac",
      },
      dark: {
        "--background": "#2e3440",
        "--foreground": "#eceff4",
        "--card": "#3b4252",
        "--card-foreground": "#eceff4",
        "--popover": "#3b4252",
        "--popover-foreground": "#eceff4",
        "--primary": "#88c0d0",
        "--primary-foreground": "#2e3440",
        "--secondary": "#81a1c1",
        "--secondary-foreground": "#2e3440",
        "--muted": "#434c5e",
        "--muted-foreground": "#d8dee9",
        "--accent": "#81a1c1",
        "--accent-foreground": "#2e3440",
        "--destructive": "#bf616a",
        "--destructive-foreground": "#eceff4",
        "--border": "#4c566a",
        "--input": "#4c566a",
        "--ring": "#88c0d0",
      },
    },
  },
  {
    name: "dracula",
    label: "Dracula",
    cssVars: {
      light: {
        "--background": "#f8f8f2",
        "--foreground": "#282a36",
        "--card": "#ffffff",
        "--card-foreground": "#282a36",
        "--popover": "#ffffff",
        "--popover-foreground": "#282a36",
        "--primary": "#bd93f9",
        "--primary-foreground": "#f8f8f2",
        "--secondary": "#ff79c6",
        "--secondary-foreground": "#f8f8f2",
        "--muted": "#e2e2dc",
        "--muted-foreground": "#6272a4",
        "--accent": "#ffb86c",
        "--accent-foreground": "#282a36",
        "--destructive": "#ff5555",
        "--destructive-foreground": "#f8f8f2",
        "--border": "#6272a4",
        "--input": "#6272a4",
        "--ring": "#bd93f9",
      },
      dark: {
        "--background": "#282a36",
        "--foreground": "#f8f8f2",
        "--card": "#44475a",
        "--card-foreground": "#f8f8f2",
        "--popover": "#44475a",
        "--popover-foreground": "#f8f8f2",
        "--primary": "#bd93f9",
        "--primary-foreground": "#282a36",
        "--secondary": "#ff79c6",
        "--secondary-foreground": "#282a36",
        "--muted": "#44475a",
        "--muted-foreground": "#f8f8f2",
        "--accent": "#8be9fd",
        "--accent-foreground": "#282a36",
        "--destructive": "#ff5555",
        "--destructive-foreground": "#f8f8f2",
        "--border": "#6272a4",
        "--input": "#6272a4",
        "--ring": "#bd93f9",
      },
    },
  }
];
